.TH flashing 1 2020-10-29
.SH NAME
flashing \- open a window flashing random colors
.SH SYNOPSIS
.B flashing
.RB [ \-h ]
.RB [ \-f ]
.RB [ \-x
.IR width ]
.RB [ \-y
.IR height ]
.RB [ \-t
.IR title ]
.SH DESCRIPTION
\fBflashing\fR is a simple program which opens up a \fBGLFW\fR window flashing random colors using \fBOpenGL\fR.
.SH OPTIONS
.TP
.B \-h
show usage.
.TP
.B \-f
turn on fullscreen mode, and the window size will be the same as your primary monitor.
.TP
.BI \-x " width"
turn on windowed mode. and set width for the window.
.TP
.BI \-y " height"
turn on windowed mode. and set height for the window.
.TP
.BI \-t " title"
set a title for the window, can be used in both modes. Default is "flashing"
.SH MODES
The program can either be in windowed mode or fullscreen mode. When both modes are enabled, it will be considered as fullscreen mode.
.SS Fullscreen Mode
The window will be a fullscreen window.
.SS Windowed Mode
The window will be a regular window with size (\fIwidth\fR, \fIheight\fR).
.SH EXAMPLE
.PP
Open a window with size (800,600):
.in +4n
.EX
$ flashing -x 800 -y 600
.EE
.PP
Open a fullscreen window with title "my window title"
.in +4n
.EX
$ flashing -f -t "my window title"
.EE
.SH WARNING
The flashing of colors may trigger epilepsy, and I AM NOT RESPONSIBLE FOR ANY DAMAGE CAUSED, so be careful.
.SH AUTHORS
tensorknower69 <62006583+tensorknower69@users.noreply.github.com>
.SH BUGS
Report them on https://github.com/tensorknower69/flashing/issues.
